type = "javascript"
account_id = '2ae5ddc12fe01a282dd014d39792077a'

[env.staging]
workers_dev = true
name = "vokabon-staging"
kv_namespaces = [ 
  { binding = "STORE", id = "99e36b1dbda843e08b6c7a037630cb2b" }
]

[env.live]
workers_dev = true
# zone_id = "4bdba9fdefc31627b48f4d841744ccd4"
# route = "https://vokabon.com/*"
name = "vokabon"
kv_namespaces = [ 
  { binding = "STORE", id = "7f90360a04d84ce88a6ec09878f20d9f" }
]
